### PR TITLE
Use Unicode escape character for pound sign (\u00A3). Fixes #3

### LINKED ISSUE #3: Compile error
```
$ ./gradlew
:clean UP-TO-DATE
:compileJava
/home/ian/p/skyprint/src/main/java/pw/ollie/skyprint/SkyCharacter.java:140: error: unmappable character for encoding UTF8
                        '�',
                         ^
:processResources
:classes
:jar
:javadoc
/home/ian/p/skyprint/src/main/java/pw/ollie/skyprint/SkyCharacter.java:140: error: unmappable character for encoding UTF8
                        '�',
                         ^
1 error
:javadocJar
:sourcesJar
:signArchives SKIPPED
:assemble
:compileTestJava UP-TO-DATE
:processTestResources UP-TO-DATE
:testClasses UP-TO-DATE
:test UP-TO-DATE
:check UP-TO-DATE
:build
:copyPlugin
:install

BUILD SUCCESSFUL
```

You may want to reformat the code?

### PR DESCRIPTION
**Pull request by macalinao**
Signed-off-by: Ian Macalinao me@ian.pw

### CODE REVIEW

**Comment by olliestanley** [comment]
u need to rebase or something and re-add it cause i just deleted the constant lol lol lol

**Comment by macalinao** [comment]
zzz

**Comment by olliestanley** [comment]
wat

**Comment by macalinao** [comment]
merge it

**Comment by olliestanley** [comment]
yey

**Comment by olliestanley** [comment]
thanks

**Pull request merged**
